### ISSUE TITLE
Logging in with spotify not possible

### ISSUE THREAD

**Issue by dennisdenk** [apricote/Listory#284]
If I try to log into Listory, the auth request fails with this error message:

![image](https://github.com/apricote/Listory/assets/19978270/b238bbde-8f26-4562-89f3-91315ca959b2)

I even tried removing the app from my account and re-authenticating. That didn't solve the problem as well.

`listory-api-1  | {"level":"error","time":1687187317338,"pid":1,"hostname":"HOSTNAME","reqId":164,"context":"SpotifyAuthFilter","err":{"type":"Error","message":"Login with Spotify failed: Error: getaddrinfo EAI_AGAIN accounts.spotify.com","stack":"InternalOAuthError: Failed to obtain access token\n    at OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:423:17)\n    at /app/node_modules/passport-oauth2/lib/strategy.js:177:45\n    at /app/node_modules/passport-spotify/lib/passport-spotify/strategy.js:81:20\n    at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (node:events:511:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at TLSSocket.socketErrorListener (node:_http_client:495:9)\n    at TLSSocket.emit (node:events:511:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:151:8)"},"msg":"Login with Spotify failed: Error: getaddrinfo EAI_AGAIN accounts.spotify.com"}
listory-api-1  | {"level":"info","time":1687187317339,"pid":1,"hostname":"9301b7574c30","reqId":164,"req":{"id":164,"method":"GET","url":"/api/v1/auth/spotify/callback?code=CODE","query":{"code":"CODE"},"params":{"0":"api/v1/auth/spotify/callback"},"headers":"[Redacted]","remoteAddress":"::ffff:172.22.0.1","remotePort":36216},"res":{"statusCode":302,"headers":"[Redacted]"},"responseTime":5006,"msg":"request completed"}
listory-api-1  | {"level":"info","time":1687187317462,"pid":1,"hostname":"HOSTNAME","reqId":165,"req":{"id":165,"method":"GET","url":"/login/failure?reason=unknown&source=spotify","query":{"reason":"unknown","source":"spotify"},"params":{"0":"login/failure"},"headers":"[Redacted]","remoteAddress":"::ffff:172.22.0.1","remotePort":36232},"res":{"statusCode":304,"headers":"[Redacted]"},"responseTime":1,"msg":"request completed"}`

**Comment by dennisdenk** [comment]
The problem was not enabling the docker iptables functioanlity and therefore loosing the container's ability to connect to any server
